### PR TITLE
update cors doc to reflect v5

### PR DESCRIPTION
**Pull request by foufrix**
update doc to reflect v5 `cors()` instead of `createCors()`

### CODE REVIEW

**Comment by foufrix** [comment]
solve #24

**Comment by kwhitley** [comment]
Hmmm... appreciate the attempt at a fix, but this one should def not be touched.  You may notice that the file is `createCors.md`, so a legacy v4 file.  Correct choice is to delete it entirely so it doesn't appear in search :)

**Comment by kwhitley** [comment]
Importantly, `cors()` (the correct v5 one) should be correctly linked throughout the docs, so if you found it in the menu (or linked from any reference to CORS), you would end up in the right place.  The problem is that search ignores all that, linking the old `createCors.md` page as the top search results for CORS.  That def creates a problem.  I've deleted the file and am waiting on it to rebuild to verify :)

**Comment by foufrix** [comment]
Oh, ok, my bad! Yep, I searched and arrived on this page, but I should have dug a bit more, did not though of this case scenario
Thanks for the fix!

**Pull request closed without merging**
